from __future__ import annotations

import os
import re
import shutil
from dataclasses import dataclass
from pathlib import Path, PurePosixPath

from .adapters import get_adapter
from .errors import ValidationError
from .hashing import directory_sha256, file_sha256
from .manifest import dump_manifest, validate_manifest
from .models import DeploymentManifest, MachineIdentity, Resource, SkillInventoryEntry

SKILL_ID_PATTERN = re.compile(r"^[a-z0-9][a-z0-9-]*$")
PROVENANCE_HEADER = (
    "<!-- Generated by dot; edit canonical sources, then run dot apply. Schema: 1. -->"
)


@dataclass(frozen=True)
class SkillSource:
    canonical_id: str
    target_id: str
    path: Path
    source_kind: str
    source_path: str
    source_id: str | None = None
    nar_hash: str | None = None
    rev: str | None = None


def _frontmatter(path: Path) -> dict[str, str]:
    try:
        text = path.read_text(encoding="utf-8")
    except UnicodeDecodeError as error:
        raise ValidationError(f"SKILL.md must be UTF-8: {path}") from error
    lines = text.splitlines()
    if not lines or lines[0] != "---":
        raise ValidationError(f"SKILL.md lacks YAML frontmatter: {path}")
    values: dict[str, str] = {}
    for line in lines[1:]:
        if line == "---":
            break
        if ":" not in line:
            raise ValidationError(f"unsupported frontmatter line in {path}: {line!r}")
        key, value = line.split(":", 1)
        values[key.strip()] = value.strip().strip('"').strip("'")
    else:
        raise ValidationError(f"unterminated YAML frontmatter: {path}")
    return values


def validate_skill(skill: SkillSource) -> None:
    if not SKILL_ID_PATTERN.fullmatch(skill.target_id):
        raise ValidationError(f"invalid target skill ID: {skill.target_id!r}")
    if skill.path.is_symlink() or not skill.path.is_dir():
        raise ValidationError(f"skill source must be a real directory: {skill.path}")
    metadata = _frontmatter(skill.path / "SKILL.md")
    if metadata.get("name") != skill.target_id:
        raise ValidationError(
            f"skill name {metadata.get('name')!r} does not match target ID "
            f"{skill.target_id!r}: {skill.path}"
        )
    if not metadata.get("description"):
        raise ValidationError(f"skill description is empty: {skill.path}")
    directory_sha256(skill.path)
    if skill.source_kind == "local":
        if skill.canonical_id != f"local:{skill.target_id}":
            raise ValidationError(f"invalid local canonical ID: {skill.canonical_id}")
    elif skill.source_kind == "external":
        if not skill.source_id or not SKILL_ID_PATTERN.fullmatch(skill.source_id):
            raise ValidationError(f"invalid external source ID: {skill.source_id!r}")
        if skill.canonical_id != f"external:{skill.source_id}/{skill.target_id}":
            raise ValidationError(f"invalid external canonical ID: {skill.canonical_id}")
        if not skill.nar_hash:
            raise ValidationError(f"external skill is missing narHash: {skill.canonical_id}")
        relative = PurePosixPath(skill.source_path)
        if relative.is_absolute() or ".." in relative.parts:
            raise ValidationError(
                f"external skill path must be relative without '..': {skill.source_path}"
            )
    else:
        raise ValidationError(f"unsupported skill source kind: {skill.source_kind}")


def discover_local_skills(root: Path) -> dict[str, SkillSource]:
    if not root.exists():
        return {}
    result: dict[str, SkillSource] = {}
    for child in sorted(root.iterdir(), key=lambda path: os.fsencode(path.name)):
        skill_id = child.name
        if not SKILL_ID_PATTERN.fullmatch(skill_id):
            raise ValidationError(f"invalid local skill directory name: {skill_id!r}")
        skill = SkillSource(
            canonical_id=f"local:{skill_id}",
            target_id=skill_id,
            path=child,
            source_kind="local",
            source_path=child.relative_to(root.parent.parent).as_posix(),
        )
        validate_skill(skill)
        result[skill.canonical_id] = skill
    return result


def validate_external_locks(repository: Path, source_ids: set[str]) -> None:
    from .jsonutil import load_json

    try:
        lock = load_json(repository / "flake.lock")
        nodes = lock["nodes"]
        root = nodes[lock["root"]]
    except (OSError, KeyError, TypeError, ValueError) as error:
        raise ValidationError(f"invalid flake.lock: {error}") from error
    for source_id in source_ids:
        reference = root.get("inputs", {}).get(source_id)
        if not isinstance(reference, str):
            raise ValidationError(f"external source {source_id!r} must be a direct root lock input")
        locked = nodes.get(reference, {}).get("locked", {})
        if not isinstance(locked.get("narHash"), str) or not locked["narHash"]:
            raise ValidationError(f"external source {source_id!r} lacks locked.narHash")


def compose_rules(repository: Path, paths: list[Path]) -> bytes:
    sections = [PROVENANCE_HEADER]
    for path in paths:
        try:
            content = (repository / path).read_text(encoding="utf-8").strip()
        except (OSError, UnicodeDecodeError) as error:
            raise ValidationError(f"cannot read canonical rules {path}: {error}") from error
        sections.append(f"<!-- Source: {path.as_posix()} -->\n{content}")
    return ("\n\n".join(sections).rstrip() + "\n").encode()


def compile_platform(
    *,
    repository: Path,
    platform: str,
    identity: MachineIdentity,
    output_root: Path,
    artifact_root: str,
    skills: list[SkillSource],
) -> DeploymentManifest:
    adapter = get_adapter(platform)
    if output_root.exists() and any(output_root.iterdir()):
        raise ValidationError(f"compiler output root is not empty: {output_root}")
    output_root.mkdir(parents=True, exist_ok=True)
    profile = identity.home / ".local/state/dotfiles/platforms" / platform / "profile"
    resources: list[Resource] = []
    inventory: list[SkillInventoryEntry] = []

    if adapter.rules_filename:
        rule_paths = [Path("ai-agent/rules/common.md")]
        agent_rule = repository / "ai-agent/rules/agents" / f"{platform}.md"
        if agent_rule.exists():
            rule_paths.append(agent_rule.relative_to(repository))
        rules_path = output_root / adapter.rules_filename
        rules_path.write_bytes(compose_rules(repository, rule_paths))
        resources.append(
            Resource(
                id=f"ai-agent.{platform}.global-rules",
                owner=f"ai-agent.{platform}",
                kind="file-link",
                target=str(identity.home / adapter.rules_target),
                link_target=str(profile / adapter.rules_filename),
                store_path=f"{artifact_root}/{adapter.rules_filename}",
                sha256=file_sha256(rules_path),
                sources=tuple(path.as_posix() for path in rule_paths),
            )
        )

    skills_root = output_root / "skills"
    skills_root.mkdir()
    target_ids: set[str] = set()
    for skill in sorted(skills, key=lambda value: value.target_id.encode("utf-8")):
        validate_skill(skill)
        if skill.target_id in target_ids:
            raise ValidationError(f"duplicate skill target ID for {platform}: {skill.target_id}")
        target_ids.add(skill.target_id)
        destination = skills_root / skill.target_id
        shutil.copytree(skill.path, destination, symlinks=True)
        digest = directory_sha256(destination)
        inventory.append(
            SkillInventoryEntry(
                canonical_id=skill.canonical_id,
                target_id=skill.target_id,
                bundle_path=f"skills/{skill.target_id}",
                directory_sha256=digest,
                source_kind=skill.source_kind,  # type: ignore[arg-type]
                source_path=skill.source_path,
                source_id=skill.source_id,
                nar_hash=skill.nar_hash,
                rev=skill.rev,
            )
        )
        resources.append(
            Resource(
                id=f"ai-agent.{platform}.skill.{skill.target_id}",
                owner=f"ai-agent.{platform}",
                kind="directory-link",
                target=str(identity.home / adapter.skills_target / skill.target_id),
                link_target=str(profile / "skills" / skill.target_id),
                store_path=f"{artifact_root}/skills/{skill.target_id}",
                directory_sha256=digest,
                sources=("ai-agent/profiles/default.nix", skill.source_path),
            )
        )
    manifest = DeploymentManifest(identity, platform, tuple(resources), tuple(inventory))
    validate_manifest(manifest)
    dump_manifest(manifest, output_root / "share/dotfiles/manifest.json")
    return manifest


def validate_static_contracts(identity: MachineIdentity) -> None:
    targets: list[tuple[str, str, str]] = []
    for platform in ("codex", "claude", "cursor"):
        adapter = get_adapter(platform)
        if adapter.rules_target:
            targets.append((platform, "file-link", str(identity.home / adapter.rules_target)))
        # Skill roots are namespaces, not owned resources. Check them as directory
        # namespaces so a future adapter cannot place rules inside another platform's
        # skill root, while leaving the roots themselves user-owned.
        targets.append((platform, "skill-namespace", str(identity.home / adapter.skills_target)))
    for index, (domain, kind, target) in enumerate(targets):
        path = Path(target)
        for other_domain, other_kind, other_target in targets[index + 1 :]:
            other = Path(other_target)
            overlap = path == other
            if kind in {"directory-link", "skill-namespace"}:
                overlap = overlap or path in other.parents
            if other_kind in {"directory-link", "skill-namespace"}:
                overlap = overlap or other in path.parents
            if overlap:
                raise ValidationError(
                    f"static ownership overlap: {domain}:{target} and {other_domain}:{other_target}"
                )
